function data()
return {
	en = {
		["mod_name"] = "ICE 4 of Deutsche Bahn",
		["mod_desc"] = "The ICE 4 is the latest development in ICE history. Slower than its predecessors, but more energy efficient and with more space and comfort. Since 2017, the new flagship of the Deutsche Bahn is on the rails. Two trains were designed with green stripes deviating from the usual design to indicate the use of green electricity at the railway. Since the summer of 2019, all power cars are covered with green stripes as Germany's fastest climate saver.\nThis mod includes also the fake variants of all models, can be optionally enabled by the ingame mod manager.",

        ["Fake"] = "Activate fake versions?",
        ["option_fake_ice4_desc"] = "You can choose if fake versions of the ICE 4 should be hidden (default) or shown in depot.",

        ["265 km/h"] = " [265 km/h]",
        ["ICE4_menu"] = "ICE 4",
		["ICE4_7tlg_name"] = "ICE 4 (7 parts) (Class 412)",
		["ICE4_12tlg_name"] = "ICE 4 (12 parts) (Class 412)",
        ["ICE4_12tlg_gruen_name"] = "ICE 4 (12 parts) (Class 412) Eco Power",
		["ICE4_7tlg_klima_name"] = "ICE 4 (7 parts) (Class 412) Climate Saver",
        ["ICE4_12tlg_klima_name"] = "ICE 4 (12 parts) (Class 412) Climate Saver",
        ["ICE4_13tlg_klima_name"] = "ICE 4 (13 parts) (Class 412) Climate Saver",
        ["ICE4_13tlg_brd_name"] = "ICE 4 (13 parts) (Class 412) Federal Republic Germany",
		["ICE4_desc"] = "As the newest part of the ICE fleet, the ICE 4 has been on the german rail network since 2017. Originally developed for a speed of 230 km/h, the top speed was later increased to 250 km/h and 265 km/h. The multiple unit offers plenty of space in the 1st and 2nd class, a board restaurant and first ever bicycle compartments in an ICE. The trains are in seven-, twelve- and thirteen-part units.",

        ["ICE4_Apmzf0812_name"] = "1st Class End Car Apmzf 0812",
        ["ICE4_Apmz1812_name"] = "1. Class Car Apmz 1812.0",
        ["ICE4_Apmz1412_name"] = "1. Class Car Apmz 1412.0",
        ["ICE4_ARmz8812_name"] = "Restaurant/1st Class Car ARmz 8812.0",
        ["ICE4_Bpmbsz6412_name"] = "2nd Class Car Bpmbsz 6412.0",
        ["ICE4_Bpmz9812_name"] = "2nd Class Car Bpmz 9812.0",
        ["ICE4_Bpmz2412_name"] = "2nd Class Car Bpmz 2412.0",
        ["ICE4_Bpmz4812_name"] = "2nd Class Car Bpmz 4812.0",
        ["ICE4_Bpmdzf5812_name"] = "2nd Class End Car Bpmdzf 5812.0",

        ["ICE4_fake_menu"] = "ICE 4 FAKE",
		["ICE4_7tlg_fake_name"] = "ICE 4 (7 parts) (Class 412) FAKE",
		["ICE4_12tlg_fake_name"] = "ICE 4 (12 parts) (Class 412) FAKE",
        ["ICE4_12tlg_gruen_fake_name"] = "ICE 4 (12 parts) (Class 412) Eco Power FAKE",
		["ICE4_7tlg_klima_fake_name"] = "ICE 4 (7 parts) (Class 412) Climate Saver FAKE",
        ["ICE4_12tlg_klima_fake_name"] = "ICE 4 (12 parts) (Class 412) Climate Saver FAKE",
        ["ICE4_13tlg_klima_fake_name"] = "ICE 4 (13 parts) (Class 412) Climate Saver FAKE",

        ["ICE4_Apmzf0812_fake_name"] = "1st Class End Car Apmzf 0812 FAKE",
        ["ICE4_Apmz1812_fake_name"] = "1. Class Car Apmz 1812.0 FAKE",
        ["ICE4_Apmz1412_fake_name"] = "1. Class Car Apmz 1412.0 FAKE",
        ["ICE4_ARmz8812_fake_name"] = "Restaurant/1st Class Car ARmz 8812.0 FAKE",
        ["ICE4_Bpmbsz6412_fake_name"] = "2nd Class Car Bpmbsz 6412.0 FAKE",
        ["ICE4_Bpmz9812_fake_name"] = "2nd Class Car Bpmz 9812.0 FAKE",
        ["ICE4_Bpmz2412_fake_name"] = "2nd Class Car Bpmz 2412.0 FAKE",
        ["ICE4_Bpmz4812_fake_name"] = "2nd Class Car Bpmz 4812.0 FAKE",
        ["ICE4_Bpmdzf5812_fake_name"] = "2nd Class End Car Bpmdzf 5812.0 FAKE",

		},
	de = {
		["mod_name"] = "ICE 4 der Deutschen Bahn",
		["mod_desc"] = "Der ICE 4 ist die neueste Entwicklung in der ICE-Geschichte. Langsamer als die Vorgänger, aber energieeffizienter und mit mehr Platz und Komfort. Seit 2017 ist das neue Flaggschiff der Deutschen Bahn auf den Schienen unterwegs. Zwei Züge wurden mit grünem Streifen abweichend zum gewohnten Design gestaltet um auf den Einsatz von Ökostrom bei der Bahn hinzuweisen. Seit Sommer 2019 werden alle Triebköpfe mit grünem Streifen beklebt als Deutschlands schnellster Klimaschützer.\nDieser Mod beinhaltet ausserdem die Fake-Variante von allen Fahrzeugen. Diese können mit dem Ingame-Mod-Manager bei Bedarf aktiviert werden.",

        ["Fake"] = "Fake-Versionen aktivieren?",
        ["option_fake_ice4_desc"] = "Schaltet die Fake-Versionen des ICE 4 ab (Standard) oder an.",

        ["265 km/h"] = " [265 km/h]",
        ["ICE4_menu"] = "ICE 4",
		["ICE4_7tlg_name"] = "ICE 4 (7-tlg) (BR 412)",
        ["ICE4_7tlg_mns_name"] = "ICE 4 (7-tlg) (BR 412) Mund-Nase-Schutz",
		["ICE4_12tlg_name"] = "ICE 4 (12-tlg) (BR 412)",
        ["ICE4_12tlg_gruen_name"] = "ICE 4 (12-tlg) (BR 412) Ökostrom",
        ["ICE4_7tlg_klima_name"] = "ICE 4 (7-tlg) (BR 412) Klimaschützer",
        ["ICE4_12tlg_klima_name"] = "ICE 4 (12-tlg) (BR 412) Klimaschützer",
        ["ICE4_13tlg_klima_name"] = "ICE 4 (13-tlg) (BR 412) Klimaschützer",
        ["ICE4_13tlg_brd_name"] = "ICE 4 (13-tlg) (BR 412) Bundesrepublik Deutschland",
		["ICE4_desc"] = "Als neuester Teil der ICE-Flotte ist der ICE 4 seit 2017 im deutschen Bahnnetz unterwegs. Urspünglich entwickelt für eine Geschwindigkeit von 230 km/h, wurde die Höchstgeschwindigkeit später auf 250 km/h und 265 km/h angehoben. Der Triebzug bietet viel Platz in der 1. und 2. Klasse, ein Bord Restaurant sowie erstmal Fahrradabteile in einem ICE. Die Züge gibt es in sieben-, zwölf- und dreizehnteiligen Einheiten.",

        ["ICE4_Apmzf0812_name"] = "1. Kl.-Endwagen Apmzf 0812",
        ["ICE4_Apmz1812_name"] = "1. Kl.-Wagen Apmz 1812.0",
        ["ICE4_Apmz1412_name"] = "1. Kl.-Wagen Apmz 1412.0",
        ["ICE4_ARmz8812_name"] = "Bordrestaurant/1. Kl.-Wagen ARmz 8812.0",
        ["ICE4_Bpmbsz6412_name"] = "2. Kl.-Wagen Bpmbsz 6412.0",
        ["ICE4_Bpmz9812_name"] = "2. Kl.-Wagen Bpmz 9812.0",
        ["ICE4_Bpmz2412_name"] = "2. Kl.-Wagen Bpmz 2412.0",
        ["ICE4_Bpmz4812_name"] = "2. Kl.-Wagen Bpmz 4812.0",
        ["ICE4_Bpmdzf5812_name"] = "2. Kl.-Endwagen Bpmdzf 5812.0",

        ["ICE4_fake_menu"] = "ICE 4 - FAKE",
		["ICE4_7tlg_fake_name"] = "ICE 4 (7-tlg) (BR 412) FAKE",
        ["ICE4_7tlg_mns_fake_name"] = "ICE 4 (7-tlg) (BR 412) Mund-Nase-Schutz FAKE",
		["ICE4_12tlg_fake_name"] = "ICE 4 (12-tlg) (BR 412) FAKE",
        ["ICE4_12tlg_gruen_fake_name"] = "ICE 4 (12-tlg) (BR 412) Ökostrom FAKE",
        ["ICE4_7tlg_klima_fake_name"] = "ICE 4 (7-tlg) (BR 412) Klimaschützer FAKE",
        ["ICE4_12tlg_klima_fake_name"] = "ICE 4 (12-tlg) (BR 412) Klimaschützer FAKE",
        ["ICE4_13tlg_klima_fake_name"] = "ICE 4 (13-tlg) (BR 412) Klimaschützer FAKE",
        ["ICE4_13tlg_brd_fake_name"] = "ICE 4 (13-tlg) (BR 412) Bundesrepublik Deutschland FAKE",

        ["ICE4_Apmzf0812_fake_name"] = "1. Kl.-Endwagen Apmzf 0812 FAKE",
        ["ICE4_Apmz1812_fake_name"] = "1. Kl.-Wagen Apmz 1812.0 FAKE",
        ["ICE4_Apmz1412_fake_name"] = "1. Kl.-Wagen Apmz 1412.0 FAKE",
        ["ICE4_ARmz8812_fake_name"] = "Bordrestaurant/1. Kl.-Wagen ARmz 8812.0 FAKE",
        ["ICE4_Bpmbsz6412_fake_name"] = "2. Kl.-Wagen Bpmbsz 6412.0 FAKE",
        ["ICE4_Bpmz9812_fake_name"] = "2. Kl.-Wagen Bpmz 9812.0 FAKE",
        ["ICE4_Bpmz2412_fake_name"] = "2. Kl.-Wagen Bpmz 2412.0 FAKE",
        ["ICE4_Bpmz4812_fake_name"] = "2. Kl.-Wagen Bpmz 4812.0 FAKE",
        ["ICE4_Bpmdzf5812_fake_name"] = "2. Kl.-Endwagen Bpmdzf 5812.0 FAKE",

		},
}
end
